ApplicationContext 需要 org.springframework.expression-3.1.1.RELEASE.jar
Exception in thread "main" java.lang.NoClassDefFoundError: org/springframework/expression/PropertyAccessor
	at org.springframework.context.support.AbstractApplicationContext.prepareBeanFactory(AbstractApplicationContext.java:538)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:439)
	at org.springframework.context.support.FileSystemXmlApplicationContext.<init>(FileSystemXmlApplicationContext.java:140)
	at org.springframework.context.support.FileSystemXmlApplicationContext.<init>(FileSystemXmlApplicationContext.java:84)
	at SpringDemo2.main(SpringDemo2.java:6)
Caused by: java.lang.ClassNotFoundException: org.springframework.expression.PropertyAccessor
	at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	... 5 more